trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Use Node 14'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Next.js app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.next'
    artifactName: 'next-build'
  displayName: 'Publish build artifacts'
